[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/index"
  status = 200
